<a href="https://colab.research.google.com/github/Ikenergy/hello-world/blob/HAMOYE-PRACTICE/HamoyeStageA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY** **PRACTICE**

In [1]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.random.random((2, 3))

array([[0.84182766, 0.84432343, 0.68189334],
       [0.20018503, 0.32949878, 0.27023098]])

In [4]:
np.full((2, 3), 44)

array([[44, 44, 44],
       [44, 44, 44]])

# **PANDAS**

## Series from dictionaries

In [5]:
import pandas as pd

In [6]:
day_series = pd.Series({'a':'Monday', 'b':'Tuesday', 'c':'Wednesday', 'd':'Thursday', 'e':'Friday', 'f':'Saturday', 'g':'Sunday'})

In [7]:
print(day_series)

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
e       Friday
f     Saturday
g       Sunday
dtype: object


In [8]:
day_series[:]

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
e       Friday
f     Saturday
g       Sunday
dtype: object

In [9]:
day_series['d':'g']

d    Thursday
e      Friday
f    Saturday
g      Sunday
dtype: object

In [10]:
day_series[3:]

d    Thursday
e      Friday
f    Saturday
g      Sunday
dtype: object

## Dataframes

In [11]:
day_df= pd.DataFrame(day_series, columns=['DAYS'])
print(day_df)

        DAYS
a     Monday
b    Tuesday
c  Wednesday
d   Thursday
e     Friday
f   Saturday
g     Sunday


In [12]:
day_df['DAYS']

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
e       Friday
f     Saturday
g       Sunday
Name: DAYS, dtype: object

In [13]:
day_df.loc['d']

DAYS    Thursday
Name: d, dtype: object

In [14]:
day_df.iloc[3]

DAYS    Thursday
Name: d, dtype: object

In [15]:
day_df.at['d','DAYS']

'Thursday'

In [16]:
day_df.iat[3,0]

'Thursday'

In [17]:
df_fuel = pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv')
df_fuel.describe()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
count      29523.000000  ...         29523.000000
mean         118.601836  ...            19.304354
std           74.178353  ...          2091.540939
min            1.000000  ...           -41.501000
25%           55.000000  ...             1.940000
50%          122.000000  ...             4.127000
75%          176.000000  ...             7.745000
max          514.000000  ...        359278.000000

[8 rows x 7 columns]

In [18]:
df_fuel.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [21]:
import numpy as np


In [22]:
df_fuel.duplicated().any()

False